--Paso 1 — Crear Base de Datos Oracle 19c
--Tabla Oracle
CREATE TABLE RESULTADOS_SOPA (
    ID NUMBER GENERATED ALWAYS AS IDENTITY,
    FECHA_JUEGO DATE,
    PALABRAS_ENCONTRADAS NUMBER,
    JUGADOR VARCHAR2(100)
);

COMMIT;